### ISSUE TITLE
Fix several issues reported by the validatior

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-grassgis-driver#25]
@bgoesswe deployed a validation tool for back-ends. The results for the GRASS GIS back-end can be found here:
https://www.geo.tuwien.ac.at/openeoct/backend/validate/4

There are several issues reported: 
- [x] /collections and /collections/collection_id sends a non-JSON media type
- [x] It seems there are issues with authentication. /credentials/basic is missing and the credentials are directly asked for at each endpoint? According to the API they just accept the Bearer Token...
- [x] /output_formats seems to still return a response compatible only to API v0.3. Basically, just move the value for formats to the root level and remove the property default.

**Comment by m-mohr** [comment]
For /collections, we currently face an error:
```json
[
  {
    "description": "An internal error occurred while catching mapset from location utm32n!"
  }, 
  400
]
```

**Comment by neteler** [comment]
> For /collections, we currently face an error:
> 
> ```json
> [
>   {
>     "description": "An internal error occurred while catching mapset from location utm32n!"
>   }, 
>   400
> ]
> ```

Sorry, hopefully just fixed in b12a60374af9a9f1a2101d984cf40672f241f2fd

**Comment by m-mohr** [comment]
Yes, works now. The collections still return a quite limited set of metadata, not even all required fields, but it works somewhat.

It seems you removed authentication altogether for now? That works, but not sure whether that's the intended behavior?

/output_formats have been fixed, great!

**Comment by hwbllmnn** [comment]
Validation now passes: https://www.geo.tuwien.ac.at/openeoct/backend/validate/6

**Comment by m-mohr** [comment]
Yes, great. Authentication is still not fluently working, but is tracked with #18

**Comment by m-mohr** [comment]
It still needs to be deployed to https://openeo.mundialis.de/api/v0.4, right?

**Comment by hwbllmnn** [comment]
Oh, my bad, I was looking at the wrong validation result... You can reopen this for now, sorry.

**Comment by neteler** [comment]
The latest version has been deployed at https://openeo.mundialis.de/api/v0.4/
